## part 1

In [ ]:
import numpy as np

def array_factory(
    mode: str,
    shape: tuple[int, ...] | int,
    value: int | float | None = None
):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.

    Parameters:
        mode (str): The type of array to create.
        shape (tuple[int, ...] | int): The shape or size of the array.
        value (int | float | None): The value used for 'full' mode.

    Returns:
        np.ndarray: The created NumPy array.
    """

    # TODO: Students implement logic here

    if mode == "zeros":
        return np.zeros(shape)

    elif mode == "ones":
        return np.ones(shape)

    elif mode == "full":
        return np.full(shape, value)

    elif mode == "identity":
        return np.eye(shape)

    else:
        raise ValueError("Invalid mode")


#Example usage:

print(array_factory("zeros", (2, 3)))

print(array_factory("ones", (2, 3)))

print(array_factory("full", (2, 2), 5))

print(array_factory("identity", 3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## part 2

In [ ]:
import numpy as np

def secure_reshape_and_stack(
    data1: list[int | float],
    data2: list[int | float],
    new_shape: tuple[int, int]
) :
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.

    Parameters:
        data1 (list[int | float]): The first dataset.
        data2 (list[int | float]): The second dataset.
        new_shape (tuple[int, int]): The new shape for the first dataset.

    Returns:
        np.ndarray: The combined dataset after reshaping and stacking.
    """

    try:
        # Convert inputs to ndarray to ensure they are processed as Tensors
        # arr = np.array(data1)

        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # Rule: Change the shape of arr1 to new_shape
        # Common use: turning a vector (1D) into a matrix (2D)
        reshaped_arr1 = arr1.reshape(new_shape)

        # Rule: Vertical stacking (vstack)
        # Requirement: Both matrices must have the same number of columns
        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        # Handle cases where reshape size doesn't match or stack columns don't match
        raise ValueError(f"Company-grade Error: {e}")

# Example usage

data1 = [1, 2, 3, 4]

data2 = [
    [5, 6],
    [7, 8]
]

result = secure_reshape_and_stack(
    data1,
    data2,
    (2, 2)
)

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
